# context.md §3: Exporter is an infrastructure adapter (not domain).
# PDF via reportlab (stdlib wrapper). CSV via stdlib csv module.
# NEVER writes to disk — all output returned as bytes.
# ZIP via stdlib zipfile module; stored in Redis by the router layer.

from __future__ import annotations

import csv
import io
import os
import zipfile
from datetime import datetime, timezone

from src.compliance.domain.fema_record import FEMARecord
from src.compliance.domain.gst_record import GSTRecord


def _now_str() -> str:
    return datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


class FEMAGSTExporter:
    """
    Generates FEMA PDF and GST CSV export bytes in-memory.

    Implements IFEMAGSTExporter Protocol.
    Uses reportlab for PDF (installed via pyproject.toml dev deps).
    Uses stdlib csv + zipfile for CSV/ZIP.

    NEVER writes to disk — all methods return bytes.
    """

    # ── FEMA PDF ──────────────────────────────────────────────────────────────

    def export_fema_pdf(self, record: FEMARecord) -> bytes:
        """
        Generate Form 15CA / 15CB equivalent PDF as bytes.

        Uses reportlab.pdfgen.canvas. Falls back to a plain-text PDF if
        reportlab is not installed (useful for unit tests without the dep).
        """
        try:
            from reportlab.lib.pagesizes import A4  # type: ignore[import-untyped]
            from reportlab.lib.units import mm  # type: ignore[import-untyped]
            from reportlab.pdfgen import canvas  # type: ignore[import-untyped]

            buf = io.BytesIO()
            c = canvas.Canvas(buf, pagesize=A4)
            width, height = A4

            # Header
            c.setFont("Helvetica-Bold", 16)
            c.drawCentredString(width / 2, height - 40 * mm, "CADENCIA TRADE PLATFORM")
            c.setFont("Helvetica-Bold", 13)
            c.drawCentredString(
                width / 2,
                height - 52 * mm,
                f"Form {record.form_type} — FEMA Compliance Record",
            )

            # Divider
            c.line(20 * mm, height - 58 * mm, width - 20 * mm, height - 58 * mm)

            # Body
            c.setFont("Helvetica", 11)
            y = height - 68 * mm
            line_height = 8 * mm

            fields = [
                ("Escrow ID", str(record.escrow_id)),
                ("Form Type", record.form_type),
                ("RBI Purpose Code", record.purpose_code.value),
                ("Buyer PAN", record.buyer_pan.value),
                ("Seller PAN", record.seller_pan.value),
                ("Amount (INR)", f"₹ {record.amount_inr.value:,.2f}"),
                ("Amount (ALGO)", f"{record.amount_algo:.6f} ALGO"),
                ("FX Rate (INR/ALGO)", f"{record.fx_rate_inr_per_algo:.6f}"),
                ("Merkle Root", record.merkle_root[:32] + "…"),
                ("Generated At", record.generated_at.strftime("%Y-%m-%d %H:%M:%S UTC")),
            ]

            for label, value in fields:
                c.setFont("Helvetica-Bold", 10)
                c.drawString(20 * mm, y, f"{label}:")
                c.setFont("Helvetica", 10)
                c.drawString(75 * mm, y, value)
                y -= line_height

            # Footer — include DATA_RESIDENCY_REGION and AUDIT_RETENTION_YEARS
            retention_years = os.environ.get("AUDIT_RETENTION_YEARS", "7")
            data_region = os.environ.get("DATA_RESIDENCY_REGION", "ap-south-1")
            c.setFont("Helvetica-Oblique", 8)
            c.drawString(
                20 * mm,
                25 * mm,
                f"Generated by Cadencia on {_now_str()} | "
                f"Retained for minimum {retention_years} years per FEMA regulations.",
            )
            c.drawString(
                20 * mm,
                20 * mm,
                f"Data residency: {data_region} | "
                f"Retention: {retention_years} years",
            )

            c.save()
            return buf.getvalue()

        except ImportError:
            # Fallback: plain-text content encoded as minimal PDF
            return _text_fallback_pdf(
                title=f"FEMA {record.form_type} Record",
                content=_fema_text(record),
            )

    # ── GST CSV ───────────────────────────────────────────────────────────────

    def export_gst_csv(self, records: list[GSTRecord]) -> bytes:
        """
        Generate GST records as UTF-8 CSV bytes.

        Columns follow GSTN GSTR-2 format (simplified for B2B trade).
        """
        buf = io.StringIO()
        writer = csv.writer(buf)

        # Header row
        writer.writerow(
            [
                "Escrow ID",
                "HSN Code",
                "Buyer GSTIN",
                "Seller GSTIN",
                "Tax Type",
                "Taxable Amount (INR)",
                "IGST Amount (INR)",
                "CGST Amount (INR)",
                "SGST Amount (INR)",
                "Total Tax (INR)",
                "Generated At",
            ]
        )

        for r in records:
            writer.writerow(
                [
                    str(r.escrow_id),
                    r.hsn_code.value,
                    r.buyer_gstin.value,
                    r.seller_gstin.value,
                    r.tax_type,
                    f"{r.taxable_amount.value:.2f}",
                    f"{r.igst_amount.value:.2f}",
                    f"{r.cgst_amount.value:.2f}",
                    f"{r.sgst_amount.value:.2f}",
                    f"{r.total_tax:.2f}",
                    r.generated_at.strftime("%Y-%m-%d %H:%M:%S UTC"),
                ]
            )

        # UTF-8 BOM prefix for Excel compatibility
        bom = b"\xef\xbb\xbf"
        return bom + buf.getvalue().encode("utf-8")

    # ── Bulk ZIP ──────────────────────────────────────────────────────────────

    def build_zip(
        self,
        fema_records: list[FEMARecord],
        gst_records: list[GSTRecord],
    ) -> bytes:
        """
        Build an in-memory ZIP containing:
          - fema/<escrow_id>.pdf  (one per FEMA record)
          - gst/gst_records.csv  (all GST records in one file)
          - audit/<escrow_id>.json (audit entry metadata per escrow)
          - manifest.json         (structured manifest with escrow IDs + timestamps)
        """
        import json

        buf = io.BytesIO()
        with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
            # FEMA PDFs
            for fr in fema_records:
                pdf_bytes = self.export_fema_pdf(fr)
                zf.writestr(f"fema/{fr.escrow_id}.pdf", pdf_bytes)

            # GST CSV (all records in one file)
            if gst_records:
                csv_bytes = self.export_gst_csv(gst_records)
                zf.writestr("gst/gst_records.csv", csv_bytes)

            # Audit JSON — one file per escrow with compliance metadata
            all_escrow_ids: set[str] = set()
            for fr in fema_records:
                eid = str(fr.escrow_id)
                all_escrow_ids.add(eid)
                audit_entry = {
                    "escrow_id": eid,
                    "fema_form_type": fr.form_type,
                    "fema_purpose_code": fr.purpose_code.value,
                    "amount_inr": str(fr.amount_inr.value),
                    "amount_algo": str(fr.amount_algo),
                    "merkle_root": fr.merkle_root,
                    "generated_at": fr.generated_at.isoformat(),
                }
                zf.writestr(
                    f"audit/{eid}.json",
                    json.dumps(audit_entry, indent=2),
                )
            for gr in gst_records:
                eid = str(gr.escrow_id)
                all_escrow_ids.add(eid)

            # Manifest JSON
            manifest = {
                "export_type": "compliance_bulk_export",
                "generated_at": _now_str(),
                "escrow_count": len(all_escrow_ids),
                "escrow_ids": sorted(all_escrow_ids),
                "fema_records": [
                    {"escrow_id": str(fr.escrow_id), "form_type": fr.form_type}
                    for fr in fema_records
                ],
                "gst_records": [
                    {"escrow_id": str(gr.escrow_id), "tax_type": gr.tax_type}
                    for gr in gst_records
                ],
                "retention_years": int(
                    os.environ.get("AUDIT_RETENTION_YEARS", "7")
                ),
                "data_residency": os.environ.get(
                    "DATA_RESIDENCY_REGION", "ap-south-1"
                ),
            }
            zf.writestr("manifest.json", json.dumps(manifest, indent=2))

        return buf.getvalue()


# ── Fallback helpers (no reportlab) ──────────────────────────────────────────


def _fema_text(record: FEMARecord) -> str:
    return (
        f"Escrow ID: {record.escrow_id}\n"
        f"Form Type: {record.form_type}\n"
        f"Purpose Code: {record.purpose_code.value}\n"
        f"Buyer PAN: {record.buyer_pan.value}\n"
        f"Seller PAN: {record.seller_pan.value}\n"
        f"Amount INR: {record.amount_inr.value}\n"
        f"Amount ALGO: {record.amount_algo}\n"
        f"FX Rate: {record.fx_rate_inr_per_algo}\n"
        f"Merkle Root: {record.merkle_root}\n"
        f"Generated: {record.generated_at.isoformat()}\n"
    )


def _text_fallback_pdf(title: str, content: str) -> bytes:
    """Minimal PDF-structured bytes for environments without reportlab."""
    text = f"%PDF-1.4\n1 0 obj\n<</Type /Catalog>>\nendobj\n% {title}\n% {content}\n"
    return text.encode("utf-8")
