# This file was automatically generated by algokit.
# To regenerate: algokit compile py contracts/escrow_contract.py --out-dir artifacts/
#
# CadenciaEscrow typed client for algokit-utils 3.x
# Wraps all ABI method calls with full type safety.
#
# context.md §3 — Offline Contract Compilation:
#   This client is generated ONCE offline and committed to VCS.
#   Runtime compilation is PROHIBITED.

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from algokit_utils import (
    AlgorandClient,
    AppClient,
    AppClientMethodCallParams,
    AppFactory,
    AppFactoryCreateMethodCallParams,
    SendParams,
)

# Path to the compiled ARC-56 contract spec
ARC56_PATH = Path(__file__).parent / "CadenciaEscrow.arc56.json"


@dataclass(frozen=True)
class EscrowState:
    """Decoded global state of a CadenciaEscrow contract instance."""

    buyer: str           # Algorand address (base32)
    seller: str          # Algorand address (base32)
    amount: int          # microALGO
    session_id: str      # Cadencia session UUID
    status: int          # 0=DEPLOYED, 1=FUNDED, 2=RELEASED, 3=REFUNDED
    frozen: int          # 0=normal, 1=frozen

    @property
    def status_label(self) -> str:
        return {0: "DEPLOYED", 1: "FUNDED", 2: "RELEASED", 3: "REFUNDED"}.get(
            self.status, "UNKNOWN"
        )

    @property
    def is_frozen(self) -> bool:
        return self.frozen == 1


class CadenciaEscrowFactory:
    """
    Factory for deploying new CadenciaEscrow contract instances.

    Usage:
        factory = CadenciaEscrowFactory(algorand)
        result = await factory.deploy(
            buyer="BUYER_ADDRESS",
            seller="SELLER_ADDRESS",
            amount_microalgo=1_000_000,
            session_id="uuid-string",
        )
        client = result.app_client
    """

    def __init__(self, algorand: AlgorandClient, creator: str) -> None:
        self._algorand = algorand
        self._creator = creator
        self._factory = AppFactory(
            algorand=algorand,
            app_spec=ARC56_PATH,
            default_sender=creator,
        )

    async def deploy(
        self,
        buyer: str,
        seller: str,
        amount_microalgo: int,
        session_id: str,
        send_params: SendParams | None = None,
    ) -> tuple["CadenciaEscrowClient", Any]:
        """
        Deploy a new CadenciaEscrow and call initialize().

        Returns (client, deploy_result).
        """
        result = await self._factory.send.create.bare(
            params=AppFactoryCreateMethodCallParams(
                method="initialize",
                args=[buyer, seller, amount_microalgo, session_id],
                send_params=send_params or SendParams(),
            )
        )
        client = CadenciaEscrowClient(
            app_id=result.app_id,
            algorand=self._algorand,
            sender=self._creator,
        )
        return client, result


class CadenciaEscrowClient:
    """
    Typed client for a deployed CadenciaEscrow contract instance.

    All methods enforce the same pre-conditions as the on-chain contract.
    context.md §12 SRS-SC-001: Every call MUST be preceded by algod.dryrun()
    in the AlgorandGateway infrastructure adapter — not enforced here.
    """

    def __init__(
        self,
        app_id: int,
        algorand: AlgorandClient,
        sender: str,
    ) -> None:
        self._app_id = app_id
        self._algorand = algorand
        self._sender = sender
        self._client = AppClient(
            app_id=app_id,
            algorand=algorand,
            app_spec=ARC56_PATH,
            default_sender=sender,
        )

    @property
    def app_id(self) -> int:
        return self._app_id

    async def fund(
        self,
        payment_amount_microalgo: int,
        send_params: SendParams | None = None,
    ) -> Any:
        """
        Fund the escrow with an atomic group [PaymentTxn + AppCallTxn].

        SRS-SC-002: payment amount must equal the stored escrow amount.
        """
        # Build atomic group: payment + app call
        atc = self._algorand.new_group()
        atc.add_payment(
            sender=self._sender,
            receiver=await self._get_app_address(),
            amount=payment_amount_microalgo,
        )
        atc.add_app_call_method_call(
            AppClientMethodCallParams(
                method="fund",
                args=[atc.build_txn_with_signer(index=0)],
                send_params=send_params or SendParams(),
            )
        )
        return await atc.send()

    async def release(
        self,
        merkle_root: str,
        send_params: SendParams | None = None,
    ) -> Any:
        """
        Release funds to seller. Creator only.

        merkle_root: hex-encoded SHA-256 Merkle root anchored on-chain.
        """
        return await self._client.send.call(
            AppClientMethodCallParams(
                method="release",
                args=[merkle_root],
                send_params=send_params or SendParams(),
            )
        )

    async def refund(
        self,
        reason: str,
        send_params: SendParams | None = None,
    ) -> Any:
        """Refund buyer. Creator only."""
        return await self._client.send.call(
            AppClientMethodCallParams(
                method="refund",
                args=[reason],
                send_params=send_params or SendParams(),
            )
        )

    async def freeze(self, send_params: SendParams | None = None) -> Any:
        """Freeze escrow. Buyer, seller, or creator."""
        return await self._client.send.call(
            AppClientMethodCallParams(
                method="freeze",
                args=[],
                send_params=send_params or SendParams(),
            )
        )

    async def unfreeze(self, send_params: SendParams | None = None) -> Any:
        """Unfreeze escrow. Creator only."""
        return await self._client.send.call(
            AppClientMethodCallParams(
                method="unfreeze",
                args=[],
                send_params=send_params or SendParams(),
            )
        )

    async def get_state(self) -> EscrowState:
        """Read and decode current global state."""
        import base64

        import algosdk

        state_raw = await self._algorand.app.get_global_state(self._app_id)

        def decode_addr(value: Any) -> str:
            if isinstance(value, bytes):
                return algosdk.encoding.encode_address(value)
            return str(value)

        def decode_str(value: Any) -> str:
            if isinstance(value, bytes):
                # ARC-4 string: 2-byte big-endian length prefix + UTF-8 content
                if len(value) >= 2:
                    length = int.from_bytes(value[:2], "big")
                    return value[2 : 2 + length].decode("utf-8", errors="replace")
                return value.decode("utf-8", errors="replace")
            return str(value)

        return EscrowState(
            buyer=decode_addr(state_raw.get("buyer", b"")),
            seller=decode_addr(state_raw.get("seller", b"")),
            amount=int(state_raw.get("amount", 0)),
            session_id=decode_str(state_raw.get("session_id", b"")),
            status=int(state_raw.get("status", 0)),
            frozen=int(state_raw.get("frozen", 0)),
        )

    async def _get_app_address(self) -> str:
        import algosdk

        return algosdk.logic.get_application_address(self._app_id)
